language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
notifications:
  email:
   - raphael.pinson@camptocamp.com
env:
  - PUPPET_GEM_VERSION=">= 3.0.0"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head
